GET http://localhost:8089/threeproject/ConsultationmodeStatistics
Accept: application/json

###
GET http://localhost:8089/threeproject/selectBycontionEntry/1/2021-06-21
Accept: application/json

###
GET http://localhost:8089/threeproject/insertincome
Accept: application/json

###
POST http://localhost:8089/threeproject/insertincome
Content-Type: application/json

{
  "addname": "admin",
  "bookdeliveryId": 12,
  "refundCount": 5,
  "bookId": 3
}

###
GET http://localhost:8089/threeproject/selectnotDetails/1/100
Accept: application/json

###
GET http://localhost:8089/threeproject/selectDetailCourse
Accept: application/json

###
#查询所有已开班的班级
GET http://localhost:8089/threeproject/selectOpen
Accept: application/json

###


PUT http://localhost:80/api/item
Content-Type: application/json

{

}

###
GET http://localhost:8089/threeproject/findFaqQuestions

#根据班级id查询班级信息
GET http://localhost:8089/threeproject/selectById/1
Accept: application/json

###
GET http://localhost:8089/threeproject/findTrainingperiods
Accept: application/json

###

GET http://localhost:8089/threeproject/findPage1/1/2
Accept: application/json

###

PUT http://localhost:8089/threeproject/updatepaystate/3
Accept: application/json

###

POST http://localhost:8089/threeproject/insertoutstanding
Content-Type: application/json

{
"feesId": 9,
"alongmoney": "1000",
"accumulated": "20000",
"addname": "admin"
}

###
GET http://localhost:8089/threeproject/selectoutstanding
Accept: application/json

###
GET http://localhost:8089/threeproject/findAlloutstanding
Accept: application/json

###
POST http://localhost:8089/threeproject/insertoutstanding
Content-Type: application/json

{}

###
GET http://localhost:8089/threeproject/selectByfeeidtoentry/1
Accept: application/json

###
GET http://localhost:8089/threeproject/selectByfeeid/1
Accept: application/json

###
GET http://localhost:8089/threeproject/selectByContion/班级名称/游泳
Accept: application/json

###
PUT http://localhost:8089/threeproject/updateClass
Content-Type: application/json

{
 "courseId": 2,
  "classroomId": 3,
  "starteddate": "2021-06-11",
  "enddate": "2021-09-11",
  "updatename":"admin",
  "updatetime": "2021-06-11",
  "classesId": 1
}

###


###
POST http://localhost:8089/threeproject/insertClass
Content-Type: application/json

{
 "classesName":"2021届春季游泳少儿游泳",
 "courseId": 1,
  "classroomId": 1,
 "teacherId": 2,
  "empId": 2,
  "StartedDate": "2021-06-11",
  "EndDate": "2021-09-11"
}

###
GET http://localhost:8089/threeproject/findEmp
Accept: application/json

###
GET http://localhost:8089/threeproject/findAllClassRoom
Accept: application/json

###


GET http://localhost:8089/threeproject/findbook
Accept: application/json

###
###查询所有课类
GET http://localhost:8089/threeproject/findClassType
Accept: application/json

###
###根据课类名称查询所有课程
GET http://localhost:8089/threeproject/selectByCourseTypeId/围棋
Accept: application/json

###查询所有学期
GET http://localhost:8089/threeproject/findSemester
Accept: application/json

###查询所有年届
GET http://localhost:8089/threeproject/findyear
Accept: application/json

###
GET http://localhost:8089/threeproject/findAllClass
Accept: application/json

###
PUT http://localhost:8089/threeproject/updatepaystate/1
Accept: application/json

###
POST http://localhost:8089/threeproject/insertEntry
Content-Type: application/json

{
  "feesName": "11",
  "registerId": 1,
  "feesReceivable": "1200",
  "feesType": 0,
  "feesAdvance": "0",
  "receipts":"1200"
}

###
GET http://localhost:8089/threeproject/selectByCourseId/2
Accept: application/json

###
GET http://localhost:8089/threeproject/selectByregisterId/4
Accept: application/json

###
GET http://localhost:8089/threeproject/selectAttentState
Accept: application/json

###
POST http://localhost:8089/threeproject/addDetails
Content-Type: application/json

{
  "courseId": 1,
  "detailcourseName": "第一阶段考试",
  "serial": "501"
}



###
GET http://localhost:8089/threeproject/findEntryFees1
Accept: application/json

###
GET http://localhost:8089/threeproject/findDetailCourses/1
Accept: application/json

###
GET http://localhost:8089/threeproject/findClassroom
Accept: application/json

###
POST http://localhost:8089/threeproject/addCourse
Content-Type: application/json

{

}

###
GET http://localhost:8089/threeproject/findPage/1/2
Accept: application/json

###
#模糊查询
GET http://localhost:8089/threeproject/findbyName/球
Accept: application/json

###
GET http://localhost:8089/threeproject/findPage
Accept: application/json


###
//查询子级菜单
GET http://localhost:8089/threeproject/findChildren
Accept: application/json

###
#查询父级菜单
GET http://localhost:8089/threeproject/findParent
Accept: application/json

###
#修改课类
POST http://localhost:8089/threeproject/addcoursetype/绘画/Tsm管理员
Content-Type: application/json


###
#查询所有课类
GET http://localhost:8089/threeproject/findcoursetype
Accept: application/json

###
