PUT http://localhost:8089/threeproject/updatepaystate/1
Accept: application/json

###
POST http://localhost:8089/threeproject/insertEntry
Content-Type: application/json

{
  "feesName": "11",
  "registerId": 1,
  "feesReceivable": "1200",
  "feesType": 0,
  "feesAdvance": "0",
  "receipts":"1200"
}

###
GET http://localhost:8089/threeproject/selectByCourseId/2
Accept: application/json

###
GET http://localhost:8089/threeproject/selectByregisterId/4
Accept: application/json

###
GET http://localhost:8089/threeproject/selectAttentState
Accept: application/json

###
POST http://localhost:8089/threeproject/addDetails
Content-Type: application/json

{
  "courseId": 1,
  "detailcourseName": "第一阶段考试",
  "serial": "501"
}



###
GET http://localhost:8089/threeproject/findEntryFees1
Accept: application/json

###
GET http://localhost:8089/threeproject/findDetailCourses/1
Accept: application/json

###
GET http://localhost:8089/threeproject/findClassroom
Accept: application/json

###
POST http://localhost:8089/threeproject/addCourse
Content-Type: application/json

{

}

###
GET http://localhost:8089/threeproject/findPage/1/2
Accept: application/json

###
#模糊查询
GET http://localhost:8089/threeproject/findbyName/球
Accept: application/json

###
GET http://localhost:8089/threeproject/findPage
Accept: application/json


###
//查询子级菜单
GET http://localhost:8089/threeproject/findChildren
Accept: application/json

###
#查询父级菜单
GET http://localhost:8089/threeproject/findParent
Accept: application/json

###
#修改课类
POST http://localhost:8089/threeproject/addcoursetype/绘画/Tsm管理员
Content-Type: application/json


###
#查询所有课类
GET http://localhost:8089/threeproject/findcoursetype
Accept: application/json

###
